version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    command: >
      /bin/sh -c "/wait-for-postgres.sh db alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/code/app
      - ./pyproject.toml:/code/pyproject.toml 
      - ./alembic.ini:/code/alembic.ini
      - ./alembic:/code/alembic
      - ./wait-for-postgres.sh:/wait-for-postgres.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    env_file:
      - .env.docker  
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: